/* JS */ gapi.loaded_2(function(_){var window=this;
_.qt=function(a,b,c,d){this.left=a;this.top=b;this.width=c;this.height=d};_.h=_.qt.prototype;_.h.clone=function(){return new _.qt(this.left,this.top,this.width,this.height)};_.h.contains=function(a){return"undefined"!=typeof _.qt&&a instanceof _.qt?this.left<=a.left&&this.left+this.width>=a.left+a.width&&this.top<=a.top&&this.top+this.height>=a.top+a.height:a.x>=this.left&&a.x<=this.left+this.width&&a.y>=this.top&&a.y<=this.top+this.height};
_.h.ceil=function(){this.left=Math.ceil(this.left);this.top=Math.ceil(this.top);this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};_.h.floor=function(){this.left=Math.floor(this.left);this.top=Math.floor(this.top);this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};_.h.round=function(){this.left=Math.round(this.left);this.top=Math.round(this.top);this.width=Math.round(this.width);this.height=Math.round(this.height);return this};
_.h.translate=_.q(9);_.rt=function(a,b){var c=a.style;"opacity"in c?c.opacity=b:"MozOpacity"in c?c.MozOpacity=b:"filter"in c&&(c.filter=""===b?"":"alpha(opacity="+100*+b+")")};_.st=function(a,b,c){var d;b instanceof _.es?(d=b.x,b=b.y):(d=b,b=c);a.style.left=_.ct(d,!1);a.style.top=_.ct(b,!1)};_.tt=function(a){return _.Ys(a,"position")};

var ut;ut=function(a,b){var c=_.Xs(a,b);return c?_.mt(a,c):0};_.vt=function(a,b){if(_.O){var c=ut(a,b+"Left"),d=ut(a,b+"Right"),e=ut(a,b+"Top"),f=ut(a,b+"Bottom");return new _.Ts(e,d,f,c)}c=_.Ws(a,b+"Left");d=_.Ws(a,b+"Right");e=_.Ws(a,b+"Top");f=_.Ws(a,b+"Bottom");return new _.Ts((0,window.parseFloat)(e),(0,window.parseFloat)(d),(0,window.parseFloat)(f),(0,window.parseFloat)(c))};_.wt=function(a){return _.vt(a,"padding")}; _.xt=function(a,b){var c={},d;for(d in a)b.call(void 0,a[d],d,a)&&(c[d]=a[d]);return c};

var yt,Ct;yt=function(a){if(_.O&&!(8<=+_.ae))return a.offsetParent;var b=_.Vg(a),c=_.Ys(a,"position"),d="fixed"==c||"absolute"==c;for(a=a.parentNode;a&&a!=b;a=a.parentNode)if(11==a.nodeType&&a.host&&(a=a.host),c=_.Ys(a,"position"),d=d&&"static"==c&&a!=b.documentElement&&a!=b.body,!d&&(a.scrollWidth>a.clientWidth||a.scrollHeight>a.clientHeight||"fixed"==c||"absolute"==c||"relative"==c))return a;return null};_.zt=function(a){var b=_.$s(a);a=_.gt(a);return new _.qt(b.x,b.y,a.width,a.height)};
_.At=function(a){for(var b=new _.Ts(0,window.Infinity,window.Infinity,0),c=_.Cs(a),d=c.R.body,e=c.R.documentElement,f=_.cs(c.R);a=yt(a);)if(!(_.O&&0==a.clientWidth||_.Nd&&0==a.clientHeight&&a==d)&&a!=d&&a!=e&&"visible"!=_.Ys(a,"overflow")){var g=_.$s(a),k=new _.es(a.clientLeft,a.clientTop);g.x+=k.x;g.y+=k.y;b.top=Math.max(b.top,g.y);b.right=Math.min(b.right,g.x+a.clientWidth);b.bottom=Math.min(b.bottom,g.y+a.clientHeight);b.left=Math.max(b.left,g.x)}d=f.scrollLeft;f=f.scrollTop;b.left=Math.max(b.left,
d);b.top=Math.max(b.top,f);c=_.os(c.wb());b.right=Math.min(b.right,d+c.width);b.bottom=Math.min(b.bottom,f+c.height);return 0<=b.top&&0<=b.left&&b.bottom>b.top&&b.right>b.left?b:null};_.Bt=function(a,b){return(b&8&&_.kt(a)?b^4:b)&-9};Ct=function(a,b){return new _.es(a.x-b.x,a.y-b.y)};
_.Dt=function(a,b,c,d,e,f,g,k,l){var m,n;if(m=c.offsetParent){var p="HTML"==m.tagName||"BODY"==m.tagName;p&&"static"==_.tt(m)||(n=_.$s(m),p||(p=(p=_.kt(m))&&_.Md?-m.scrollLeft:!p||_.Ld&&_.Zd("8")||"visible"==_.Ys(m,"overflowX")?m.scrollLeft:m.scrollWidth-m.clientWidth-m.scrollLeft,n=Ct(n,new _.es(p,m.scrollTop))))}m=n||new _.es;n=_.zt(a);if(p=_.At(a)){var w=new _.qt(p.left,p.top,p.right-p.left,p.bottom-p.top),p=Math.max(n.left,w.left),y=Math.min(n.left+n.width,w.left+w.width);if(p<=y){var v=Math.max(n.top,
w.top),w=Math.min(n.top+n.height,w.top+w.height);v<=w&&(n.left=p,n.top=v,n.width=y-p,n.height=w-v)}}p=_.Cs(a);v=_.Cs(c);p.R!=v.R&&(y=p.R.body,v=_.bt(y,v.wb()),v=Ct(v,_.$s(y)),!_.O||9<=+_.ae||_.ls(p)||(v=Ct(v,_.ks(p))),n.left+=v.x,n.top+=v.y);a=_.Bt(a,b);b=n.left;a&4?b+=n.width:a&2&&(b+=n.width/2);b=new _.es(b,n.top+(a&1?n.height:0));b=Ct(b,m);e&&(b.x+=(a&4?-1:1)*e.x,b.y+=(a&1?-1:1)*e.y);var x;if(g)if(l)x=l;else if(x=_.At(c))x.top-=m.y,x.right-=m.x,x.bottom-=m.y,x.left-=m.x;e=x;l=b.clone();x=_.Bt(c,
d);d=_.gt(c);a=k?k.clone():d.clone();k=l;l=a;k=k.clone();l=l.clone();a=0;if(f||0!=x)x&4?k.x-=l.width+(f?f.right:0):x&2?k.x-=l.width/2:f&&(k.x+=f.left),x&1?k.y-=l.height+(f?f.bottom:0):f&&(k.y+=f.top);g&&(e?(f=k,x=l,a=0,65==(g&65)&&(f.x<e.left||f.x>=e.right)&&(g&=-2),132==(g&132)&&(f.y<e.top||f.y>=e.bottom)&&(g&=-5),f.x<e.left&&g&1&&(f.x=e.left,a|=1),g&16&&(b=f.x,f.x<e.left&&(f.x=e.left,a|=4),f.x+x.width>e.right&&(x.width=Math.min(e.right-f.x,b+x.width-e.left),x.width=Math.max(x.width,0),a|=4)),f.x+
x.width>e.right&&g&1&&(f.x=Math.max(e.right-x.width,e.left),a|=1),g&2&&(a=a|(f.x<e.left?16:0)|(f.x+x.width>e.right?32:0)),f.y<e.top&&g&4&&(f.y=e.top,a|=2),g&32&&(b=f.y,f.y<e.top&&(f.y=e.top,a|=8),f.y+x.height>e.bottom&&(x.height=Math.min(e.bottom-f.y,b+x.height-e.top),x.height=Math.max(x.height,0),a|=8)),f.y+x.height>e.bottom&&g&4&&(f.y=Math.max(e.bottom-x.height,e.top),a|=2),g&8&&(a=a|(f.y<e.top?64:0)|(f.y+x.height>e.bottom?128:0)),g=a):g=256,a=g);f=new _.qt(0,0,0,0);f.left=k.x;f.top=k.y;f.width=
l.width;f.height=l.height;g=a;g&496||(_.st(c,new _.es(f.left,f.top)),a=new _.ds(f.width,f.height),d==a||d&&a&&d.width==a.width&&d.height==a.height||(f=a,d=_.ls(_.Cs(_.Vg(c))),!_.O||_.Zd("10")||d&&_.Zd("8")?(c=c.style,_.Md?c.MozBoxSizing="border-box":_.Nd?c.WebkitBoxSizing="border-box":c.boxSizing="border-box",c.width=Math.max(f.width,0)+"px",c.height=Math.max(f.height,0)+"px"):(k=c.style,d?(d=_.wt(c),c=_.pt(c),k.pixelWidth=f.width-c.left-d.left-d.right-c.right,k.pixelHeight=f.height-c.top-d.top-d.bottom-
c.bottom):(k.pixelWidth=f.width,k.pixelHeight=f.height))));return g};_.Et=function(a){return new _.Ts(a.top,a.left+a.width,a.top+a.height,a.left)};_.Ft=function(a){if(1==a.nodeType)return _.at(a);a=a.changedTouches?a.changedTouches[0]:a;return new _.es(a.clientX,a.clientY)};_.Gt=function(a,b,c){c||(a=a.parentNode);for(c=0;a;){if(b(a))return a;a=a.parentNode;c++}return null};

_.Ht=function(a){a=a.className;return _.t(a)&&a.match(/\S+/g)||[]};
_.It=function(){var a=window,b=a.document,c=0;if(b){var c=b.body,d=b.documentElement;if(!d||!c)return 0;a=_.hs(a).height;if(_.$r(b)&&d.scrollHeight)c=d.scrollHeight!=a?d.scrollHeight:d.offsetHeight;else{var b=d.scrollHeight,e=d.offsetHeight;d.clientHeight!=e&&(b=c.scrollHeight,e=c.offsetHeight);c=b>a?b>e?b:e:b<e?b:e}}return c};_.Jt=function(a){this.Ca=a;this.R=a.Ub()};_.Jt.prototype.Va=function(){Kt(this)};_.Jt.prototype.onBeforeParentOpen=_.Jt.prototype.Va;
var Kt=function(a){var b=a.Ca.Ec();if(a.R.anchorBox&&b&&b.rb())b=_.$s(b.rb()),a.R.anchorBox.left+=b.x,a.R.anchorBox.top+=b.y;else{b=a.R.anchor;if("_default"!=b&&"_iframe"!=b){var c=_.Ns(b);if(c)a.R.anchorBox=_.zt(c);else{_.Kb("Anchor not found in DOM: "+b+'. Falling back to "_default".');a.R.anchor="_default";return}}"_iframe"==b&&(b=_.os(),a.R.anchorBox=new _.qt(0,0,b.width,b.height))}a.R.anchor=""};
_.Lt=function(a){_.Jt.call(this,a)};_.D(_.Lt,_.Jt);_.Lt.prototype.open=function(){var a=this.R,b=window.document.createElement("ins");window.document.getElementById(a.container).appendChild(b);b.style.display="block";_.R(b,a.containerCss);this.Ca.Ue(b);this.Ca.Ee(b)};_.Lt.prototype.Zc=function(){window.document.getElementById(this.Ca.id).style.height=this.Ca.height+"px"};_.Lt.prototype.close=function(){_.Zg(this.Ca.Cb());_.Zg(this.ra);this.ra=null};
_.Ot=function(a){if(a.ra)return a.ra;var b=a.R;!b.anchorBox&&b.anchor&&Kt(a);var c=a.Ca.Ec();if("_default"==b.anchor&&c){var d=_.zt(_.Ns(c.Cb()));b.anchorBox=d}if(!b.anchorBox)return _.Kb("No anchor box defined."),null;b=new _.es(b.anchorBox.left,b.anchorBox.top);c&&(c=_.bt(c.rb(),window),a.Ka=new _.es,a.Ka.x=c.x,a.Ka.y=c.y,b.x+=c.x,b.y+=c.y,_.Mt(b));a.Eb=b;c=_.Nt(a,!0);a.ra=window.document.createElement("ins");a.ra.style.cssText=c;window.document.body.appendChild(a.ra);return a.ra};
_.Nt=function(a,b){var c=a.R;return"position: absolute !important;background-color: transparent !important;left: "+a.Eb.x+"px !important;top: "+a.Eb.y+"px !important;width: "+c.anchorBox.width+"px !important;height: "+c.anchorBox.height+"px !important;z-index: -10000 !important;display: "+(b?"block":"none")+" !important;"};
_.Pt=function(a,b){var c=0,d=0;if(b.pageX||b.pageY)c=b.pageX,d=b.pageY;else if(b.clientX||b.clientY){var c=b.target?b.target:b.srcElement,e;c.ownerDocument&&c.ownerDocument.parentWindow?e=c.ownerDocument.parentWindow:e=window;d=c=0;_.O?(c=e.document.documentElement.scrollLeft,d=e.document.documentElement.scrollTop):(c=e.pageXOffset,d=e.pageYOffset);c=b.clientX+c;d=b.clientY+d}e=new _.es(c,d);return(c=_.Et(_.zt(a)))&&c.contains(e)};
_.Mt=function(a){var b=window,c=window.document.body,d=_.$s(c),b=c.currentStyle||b.getComputedStyle(c,"");b.position&&"static"!=b.position&&(a.x-=d.x,a.y-=d.y)};_.Qt=function(a){var b=a.Ca.Ec()&&a.Ca.Ec().Cb(),b=b&&b.style.zIndex?(0,window.parseInt)(b.style.zIndex,10)+1:0;return Math.min(2147483647,Math.max(2E9,a.R.zIndex||b))};
var Rt,St,Tt;Rt={"bottom-center":1,"bottom-end":13,"bottom-left":1,"bottom-right":5,"bottom-start":9,"left-bottom":1,"left-center":0,"left-top":0,"right-bottom":5,"right-center":4,"right-top":4,"top-center":0,"top-end":12,"top-left":0,"top-right":4,"top-start":8};St={"bottom-center":!0,"top-center":!0};Tt={"left-center":!0,"right-center":!0};
_.Ut=function(a,b,c,d,e){e=e||{x:0,y:0};if(St[b]){var f=_.gt(a).width/2;e.x="top-right"==d||"bottom-right"==d?e.x+f:e.x-f}St[d]&&(f=_.gt(c).width/2,e.x+=f);Tt[b]&&(f=_.gt(a).height/2,e.y="right-bottom"==d||"left-bottom"==d?e.y+f:e.y-f);Tt[d]&&(e.y+=_.gt(c).height/2);_.Dt(c,Rt[d],a,Rt[b],new _.es(e.x,e.y));d=_.Gt(a,function(a){if(a==window.document)return!1;a=_.tt(a);return!!a&&"static"!=a});c=b=0;d&&(c=_.$s(d),b=-c.x,c=-c.y);a=a.style;(0,window.parseInt)(a.left,10)<b&&(a.left=b+"px");(0,window.parseInt)(a.top, 10)<c&&(a.top=c+"px")};
_.Vt=function(a){_.Jt.call(this,a.Ca);this.va=a;this.S=[]};_.D(_.Vt,_.Lt);_.Vt.prototype.Va=function(){this.va.Va()};_.Vt.prototype.onBeforeParentOpen=_.Vt.prototype.Va;_.Vt.prototype.open=function(){this.va.open();(this.R.closeClickDetection||this.R.hideClickDetection)&&Wt(this)};_.Vt.prototype.open=_.Vt.prototype.open;_.Vt.prototype.Zc=function(a){this.va.Zc(a)};_.Vt.prototype.onready=_.Vt.prototype.Zc;_.Vt.prototype.U=function(a){this.va.onRenderStart&&this.va.onRenderStart(a)};
_.Vt.prototype.onRenderStart=_.Vt.prototype.U;_.Vt.prototype.close=function(){if(this.R.closeClickDetection||this.R.hideClickDetection)(0,_.id)(this.S,function(a){_.Te(a)}),this.S=[];this.va.close()};_.Vt.prototype.close=_.Vt.prototype.close;var Wt=function(a){(0,_.id)(["click","touchstart"],(0,_.u)(function(a){this.S.push(_.P(window.document,a,(0,_.u)(this.T,this),!0))},a))};_.Vt.prototype.T=function(a){_.Pt(this.Ca.Cb(),a)||(this.R.hideClickDetection&&this.va.show?this.va.show(!1):this.close())};

_.LG=function(a){_.Jt.call(this,a.Ca);this.va=a;this.S=null};_.D(_.LG,_.Lt);_.LG.prototype.open=function(){this.R.targetPos=this.R.targetPos||"top-start";this.R.anchorPos=this.R.anchorPos||"bottom-start";var a=_.Ot(this),b=this.Ca.Cb();b?(b.style.visibility="hidden",b.style.position="absolute",a.parentNode.appendChild(b)):this.va.open()};_.LG.prototype.open=_.LG.prototype.open;
_.LG.prototype.Zc=function(){if(this.R.closeClickDetection){var a=this,b=function(b){_.Pt(a.Ca.Cb(),b)||(a.Ca.close(),a.S=null)};window.document.R?(window.document.R("click",b),this.S=function(){window.document.removeEventListener("click",b,!1)}):window.document.attachEvent&&(window.document.attachEvent("onclick",b),this.S=function(){window.document.detachEvent("onclick",b)})}var c=this.Ca.Cb();window.document.getElementById(this.Ca.id).style.height=this.Ca.height+"px";var d=_.Ot(this);d&&_.Ut(c,
this.R.targetPos,d,this.R.anchorPos,{x:this.R.leftOffset||0,y:this.R.topOffset||0});c.style.visibility="visible"};_.LG.prototype.onready=_.LG.prototype.Zc;_.LG.prototype.close=function(){this.va.close();this.S&&this.S()};_.LG.prototype.close=_.LG.prototype.close;
var NG;_.MG=function(a){_.Jt.call(this,a)};_.D(_.MG,_.Lt);NG=["transition","WebkitTransition","MozTransition","OTranstion","msTransition"];_.OG=function(a,b){a.S=window.document.createElement("div");var c={position:"absolute",top:"-10000px",zIndex:_.Qt(a)};a.R.width&&(c.width=a.R.width+"px");for(var d in c)a.S.style[d]=c[d];(b||window.document.body).appendChild(a.S)};_.MG.prototype.open=function(a){this.Ca.Gd("updateContainer",(0,_.u)(this.T,this));_.OG(this,a);this.Ca.Ee(this.S);this.Ca.Ue(this.S)};
_.MG.prototype.open=_.MG.prototype.open;_.MG.prototype.Zc=function(){var a=PG(this);if(a){var b=window.document.getElementById(this.Ca.Ja());b.style.height=a.height+"px";b.style.width=a.width+"px";this.Ca.width=a.width;this.Ca.height=a.height;b.style.boxShadow="0 4px 16px rgba(0, 0, 0, 0.3)"}};_.MG.prototype.onready=_.MG.prototype.Zc;_.MG.prototype.close=function(){this.S.parentNode&&this.S.parentNode.removeChild(this.S)};_.MG.prototype.close=_.MG.prototype.close;
_.MG.prototype.T=function(a,b,c){var d=this.Ca.Cb();d&&(a?(QG(this,b,c),d.style.opacity=0,d.style.display="",window.setTimeout((0,_.u)(function(){RG(d,!0);d.style.opacity=1},this),0)):(d.style.display="none",RG(d,!1),d.style.opacity=0))};
var RG=function(a,b){for(var c=0;c<NG.length;c++)a.style[NG[c]]=b?"opacity .13s linear":""},QG=function(a,b,c){var d=a.Ca.Ec();b+=10;c+=10;if(_.M.$a&&(d&&(d=_.bt(d.Cb(),window),b+=d.x,c+=d.y),d=PG(a))){var e=_.os(window),f=_.gs(window.document);e.width&&(b=Math.min(b,e.width+f.x-d.width-8),c+d.height>e.height+f.y-8&&(c-=20+d.height,c=Math.max(c,Math.min(f.y+1,_.It()-d.height))))}a=a.Ca.Cb();a.style.left=b+"px";a.style.top=c+"px"},PG=function(a){return a.Ca.width&&a.Ca.height?{width:a.Ca.width,height:a.Ca.height}: (a=a.Ca.rb())&&a.offsetWidth&&a.offsetHeight?{width:a.offsetWidth,height:a.offsetHeight}:null};
_.SG=function(a){_.Jt.call(this,a)};_.D(_.SG,_.Lt);_.SG.prototype.T=null;_.SG.prototype.U=null;_.SG.prototype.S=null;var TG={end:"start",left:"right",right:"left",start:"end"},UG={top:"bottom",bottom:"top"};_.SG.prototype.open=function(){var a=window.document.createElement("div");_.R(a,{top:"-10000px",position:"absolute",zIndex:_.Qt(this)});_.Ot(this).parentNode.appendChild(a);this.Ca.Ue(a);this.Ca.Ee(a)};_.SG.prototype.open=_.SG.prototype.open;
_.SG.prototype.Zc=function(){var a=window.document.getElementById(this.Ca.id);a.style.height=this.Ca.height+"px";a.style.width=this.Ca.width+"px";a.style.boxShadow="0 4px 16px rgba(0, 0, 0, 0.3)";var b=this.Ca.Cb();b.style.lineHeight=0;var c=_.Ot(this),d=this.R.targetPos||"top-start",e=this.R.anchorPos||"bottom-start",f=this.R.leftOffset||0,g=this.R.topOffset||0;_.Ut(b,d,c,e,{x:f,y:g});var k=_.os(window),l=_.gs(window.document),m=b.offsetLeft<l.x||b.offsetLeft+b.offsetWidth>k.width+l.x,k=b.offsetTop<
l.y||b.offsetTop+b.offsetHeight>k.height+l.y,d=VG(d,m,k),e=VG(e,m,k);_.Ut(b,d,c,e,{x:f*(m?-1:1),y:g*(k?-1:1)});b.style.visibility="visible";this.T=_.P(window.document,"mouseover",(0,_.u)(function(b){b.target===a&&this.S&&(window.clearTimeout(this.S),this.S=null)},this));this.U=_.P(window.document,"mouseout",(0,_.u)(function(b){b.target===a&&(this.S=window.setTimeout((0,_.u)(this.Ca.close,this.Ca),1E3))},this))};_.SG.prototype.onready=_.SG.prototype.Zc;
var VG=function(a,b,c){a=a.split("-");for(var d=0;2>d;d++)b&&TG[a[d]]&&(a[d]=TG[a[d]]),c&&UG[a[d]]&&(a[d]=UG[a[d]]);return a.join("-")};_.SG.prototype.close=function(){this.T&&(_.Te(this.T),_.Te(this.U),this.U=this.T=null);this.S&&(window.clearTimeout(this.S),this.S=null);_.SG.qa.close.call(this)};_.SG.prototype.close=_.SG.prototype.close;

var $O,aP,bP;for(_.ZO=function(a){return{Ub:function(){return a},Ec:function(){return a.openerIframe}}},$O=function(a){(new _.Jt(_.ZO(a))).Va()},aP="bubble circlepicker float hover hover-menu slide-menu".split(" "),bP=0;bP<aP.length;bP++)_.sn[aP[bP]]=$O;

_.vn.hover=function(a){var b=new _.MG(_.ZO(a));_.OG(b,a.where);a.where=b.S;a.onClose=function(){b.close()};a.onRestyle=function(a){if(a.updateContainer){var d=a.updateContainer;b.T(d.visible,d.x,d.y)}a.width&&(b.Ca.width=a.width);a.height&&(b.Ca.height=a.height)};a.onCreate=function(c){b.Ca=c;c.Ec=function(){return a.openerIframe};c.register("_ready",(0,_.u)(b.Zc,b),_.en);c.updateContainer=function(a,c,f){b.T(a,c,f)}}};

var iL=function(a,b){this.R=a;this.Hh=b};iL.prototype.Vo=function(){this.R.oc(this.Hh)};_.jL=function(a){this.w=this.Lb=a;this.n=null;this.slf=0;this.ssh=!1;this.sen=!0;this.shl=this.itm=null};_.jL.prototype.sm=function(a,b){this.Lb.Mj(new iL(a,this));this.n=b};_.jL.prototype.sh=function(){this.Lb.show()};_.jL.prototype.hi=function(){this.Lb.jc()};_.jL.prototype.cl=function(){this.Lb.close()};_.jL.prototype.en=function(){this.Lb.enable()};_.jL.prototype.di=function(){this.Lb.disable()};_.jL.prototype.hl=function(a){this.Lb.GI(a)};_.jL.prototype.vr=function(a,b){this.Lb.lJ(a,b)};

_.Um.V("ytsubscribe",function(a,b){var c=_.Um.S;c&&_.Um.W({role:"ytsubscribe",iframe:c,data:b},{role:"ytrelay",iframe:a})},void 0,_.en);
var nP=function(a){a.R.os(a.Hh)},oP=function(a){this.Hh=a;this.Od=0;this.Zl=!1;this.Gx=!0;this.mh=null};oP.prototype.Mg=function(){return this.Hh};var pP=function(a){return 5==a.Od||4==a.Od};oP.prototype.isEnabled=function(){return this.Gx};oP.prototype.Hb=function(a){this.Gx=a};
var qP=function(a,b,c){this.R=a||{};this.S=b||0;this.U=c||0;a={};b=(0,_.u)(this.Xx,this);a.fc=b;b=(0,_.u)(this.Ot,this);a.rc=b;b=(0,_.u)(this.Cu,this);a.sc=b;b=(0,_.u)(this.Bl,this);a.hc=b;b=(0,_.u)(this.Ek,this);a.cc=b;b=(0,_.u)(this.qz,this);a.os=b;b=(0,_.u)(this.pz,this);a.or=b;b=(0,_.u)(this.nz,this);a.oh=b;b=(0,_.u)(this.lz,this);a.oc=b;b=(0,_.u)(this.mz,this);a.oe=b;b=(0,_.u)(this.oz,this);a.oi=b;this.T=a};_.h=qP.prototype;
_.h.Ot=function(a,b,c){try{a+=null!=b?"_"+b:"",c.sm(this.T,a),this.R[a]=new oP(c)}catch(d){return!1}return!0};_.h.Xx=function(a,b){var c=this.R[a+(null!=b?"_"+b:"")];return c?c.Mg():null};_.h.Cu=function(a){var b=rP(this,a);if(b&&(2==b.Od||3==b.Od)&&b.isEnabled()&&!b.Zl){try{a.sh()}catch(c){}b.Zl=!0}};_.h.Bl=function(a){var b=rP(this,a);if(b&&(2==b.Od||3==b.Od||pP(b))&&b.Zl){try{a.hi()}catch(c){}b.Zl=!1}};_.h.Ek=function(a){var b=rP(this,a);if(b&&5!=b.Od){try{this.Bl(a),a.cl()}catch(c){}sP(this,b)}};
_.h.qz=function(a){(a=rP(this,a))&&0==a.Od&&(tP(this,a),a.Od=1)};var tP=function(a,b){if(a.S){var c=(0,window.setTimeout)((0,_.u)(function(){pP(b)||uP(this,b)},a),a.S);b.mh=c}else uP(a,b)},uP=function(a,b){var c=a.U-a.S;0<c&&(c=(0,window.setTimeout)((0,_.u)(function(){pP(b)||(b.Od=4,this.Ek(b.Mg()))},a),c),b.mh=c)},vP=function(a){null!=a.mh&&((0,window.clearTimeout)(a.mh),a.mh=null)};_.h=qP.prototype;_.h.pz=function(a){(a=rP(this,a))&&!pP(a)&&1==a.Od&&(vP(a),a.Od=3)};
_.h.nz=function(a){(a=rP(this,a))&&!pP(a)&&(a.Zl=!1)};_.h.lz=function(a){var b=rP(this,a);if(b&&!pP(b)){try{this.Bl(a)}catch(c){}sP(this,b)}};_.h.mz=function(a){(a=rP(this,a))&&!pP(a)&&(a.Od=4,this.Ek(a.Mg()))};_.h.oz=function(a,b){var c=rP(this,a);c&&!pP(c)&&2<=b&&4>=b&&!pP(c)&&(vP(c),c.Od=2)};var sP=function(a,b){vP(b);b.Od=5;var c=a.R,d;for(d in c)c[d]==b&&delete c[d]},rP=function(a,b){return a.R[b.n]},wP=function(){qP.call(this)};_.D(wP,qP);var xP=function(a){this.R=a};_.h=xP.prototype;
_.h.Ot=function(a,b,c){return this.R.rc(a,b,c)};_.h.Xx=function(a,b){return this.R.fc(a,b)};_.h.Cu=function(a){this.R.sc(a)};_.h.Bl=function(a){this.R.hc(a)};_.h.Ek=function(a){this.R.cc(a)};_.h.qz=function(a){this.R.os(a)};_.h.pz=function(a,b){this.R.or(a,b)};_.h.nz=function(a){this.R.oh(a)};_.h.lz=function(a){this.R.oc(a)};_.h.mz=function(a,b,c,d,e,f){this.R.oe(a,b,c,d,e,f)};_.h.oz=function(a,b,c,d){this.R.oi(a,b,c,d)};
var yP=function(){return window.___jsl.man},zP=function(a){if(window.___jsl.man)a(window.___jsl.man);else{var b=function(){var b=new wP;window.___jsl.man=b;a(b)};if(window.gbar){var c=function(){if(window.gbar.wg){var c=new xP(window.gbar.wg);window.___jsl.man=c;a(c)}else b()};window.gbar.wg?c():window.gbar.qm(c)}else b()}};
var AP={contactid:!0,cdu:!0,cmp:!0,email:!0,hl:!0,n:!0,m:!0,p:!0,src:!0,userid:!0,sp:!0,ytid:!0};_.Fd({nm:!0,s:!0,pr:!0,v:!0},AP);var BP=/(?:^|\s)g-(?:hovercard|profile)(?:$|\s)/,CP={loadHovercardDelay:250,loadDelay:150,hoverDelay:500,closeDelay:500},DP=0,EP=function(a){return window.document.body==a?"body":a.__cardid||null},FP=function(a){var b=EP(a);b||(b=a.__cardid=DP++);return b},GP=function(a){var b=a.className||"getAttribute"in a&&a.getAttribute("class");return b&&BP.test(b)||"getAttribute"in a&&a.getAttribute("oid")&&36==_.F("card/p")?!0:"G:HOVERCARD"==a.tagName.toUpperCase()},HP=function(a,b){var c={};_.Fd(c,CP,_.F("iframes/card")||
{},_.F("card")||{});for(var d=[],e=a;e;e=e.parentNode){var f=EP(e);f&&b[f]&&d.push(b[f])}(0,_.id)(d.reverse(),function(a){_.Fd(c,a)});d="G:HOVERCARD"==a.tagName.toUpperCase()?"":"data-";e=a.attributes;for(f=0;f<e.length;f++)_.Wc(e[f].name,d)&&(c[e[f].name.substring(d.length)]=e[f].value);"getAttribute"in a&&a.getAttribute("oid")&&36==_.F("card/p")&&(c.ytid=a.getAttribute("oid"));!c.userid&&"A"==a.tagName.toUpperCase()&&a.pathname&&(d=a.pathname.match(/^\/?(\d+)$/),/\.google\.com$/.test(a.hostname)&& d&&(c.userid=d[1]));c.hl||(c.hl=_.F("lang")||_.K.nc().hl||void 0);c.m=c.entity;c.src=c.source;delete c.entity;delete c.source;return c},IP=function(a,b){var c=b[a];_.Vc(c)||(c=CP[a]);return 0>c?0:c};
var JP=function(a){this.S=a;this.Hh=new _.jL(this);this.T=!1;this.U=0};_.h=JP.prototype;_.h.Mg=function(){return this.Hh};
_.h.load=function(a){nP(this.$b);a=_.xt(a,function(a,b){return AP[b]&&null!=a});a.origin=window.location.protocol+"//"+window.location.host;var b=this,c=this.S,d={_event:function(a){if(!(a.timestamp<c.Ia)){"sgcp_ams"==a.event?(c.ua=!0,c.Ka=!1):c.ua&&"mouseover"==a.event?c.Ka=!0:c.ua&&"mouseout"==a.event?c.Ka=!1:"sgcp_amh"==a.event&&(c.ua=!1,c.Ka||KP(c));if("mouseover"==a.event||"sgcp_ams"==a.event)window.clearTimeout(c.V),c.V=null;if(a.cpid){for(var b=window.document.getElementById(a.cpid);b&&"BODY"!=
b.parentNode.tagName;)b=b.parentNode;c.Ra=b}a.fromCard&&"mouseout"==a.event&&KP(c)}},_ready:(0,_.u)(this.cI,this),version:function(a){LP(c,c.$,{type:"circles_changed",version:a.v})},loaded:function(a){a.ri==b.U&&b.V()},rendered:function(){var a=b.S.W,c=_.ks(_.Cs((window||_.r||window).document));MP(b,!0,a.x+c.x,a.y+c.y);a=b.S;LP(a,a.$,{type:"show",frame:b.R})},renderfailed:function(){MP(b,!1,0,0)},disposed:function(){b.R.close()},cardAction:function(a){NP(c,a)}},e=":card";!_.F("iframes/card/url")&&
_.F("iframes/hovercard/url")&&(e=":hovercard");a=_.Bm(_.Cm(_.Dm(_.Jm(_.Km(new _.Am({disableMultiLevelParentRelay:!0,hover:!0}),d),_.en),a),"hover"),e);_.F("card/relayOpenTop")&&(_.Em(a,-1),_.In(_.Fm(a),"_default"));_.Um.open(a.value(),(0,_.u)(function(a){this.R=a},this))};_.h.cI=function(){this.T=!0;var a=this.$b;a.R.or(a.Hh,{});a=this.S;a.R&&a.dt(a.R)};_.h.Mj=function(a){this.$b=a};_.h.GI=function(a){this.R.send("getHealthc",void 0,a,_.en)};_.h.lJ=function(a,b){this.R.send("getVarc",a,b,_.en)};
var MP=function(a,b,c,d){a.R.updateContainer?a.R.updateContainer(b,c,d):a.R.kp({updateContainer:{visible:b,x:c,y:d}})};_.h=JP.prototype;_.h.show=function(){MP(this,!0,0,-1E4);this.R.send("render",void 0,void 0,_.en)};_.h.jc=function(){this.R.send("hide",void 0,void 0,_.en);MP(this,!1,0,0);var a=this.S;LP(a,a.$,{type:"hide"});a.$=null;a.Xa=null};_.h.close=function(){this.R.send("dispose",void 0,void 0,_.en)};_.h.enable=function(){};_.h.disable=function(){};
var OP=function(){this.ub=0;this.Eb=[];this.ra={};this.Fa={};this.Ba={};this.Ia=this.V=this.S=this.va=this.Xa=this.$=this.U=this.R=this.T=null;this.W={x:0,y:0};this.Ka=this.ua=!1;this.Ra=null;this.ya=new _.sf;_.me("gapi.load")("gapi.iframes.style.slide-menu")},PP=0,QP=function(a,b,c,d){var e=FP(b),e=a.Ba[e]||(a.Ba[e]={});e[c]||(e[c]=d=(0,_.u)(d,a),b.addEventListener?b.addEventListener(c,d,"focus"==c||"blur"==c):("focus"==c?c="focusin":"blur"==c&&(c="focusout"),b.attachEvent("on"+c,d)))},RP=function(a,
b,c){(a=a.Ba[FP(b)])&&a[c]&&(b.addEventListener?b.removeEventListener(c,a[c],"focus"==c||"blur"==c):b.detachEvent("focus"==c?"onfocusin":"blur"==c?"onfocusout":"on"+c,a[c]),delete a[c])},SP=function(a,b){var c=a.Ba[b.id];if(c)for(var d in c)c.hasOwnProperty(d)&&RP(a,b,d)};
OP.prototype.watch=function(a,b,c){if(a=a||window.document.body){this.ub++;var d=FP(a);b&&(this.ra[d]=b);c&&(this.Fa[d]=c);QP(this,a,"mouseover",this.Sx);QP(this,a,"mouseout",this.Ls);QP(this,a,"mousedown",this.Rx);QP(this,a,"focus",this.Sx);QP(this,a,"blur",this.Ls);QP(this,window.document.body,"mouseout",this.Ls);QP(this,window.document.body,"mousedown",this.Rx)}else window.setTimeout((0,_.u)(this.watch,this),100)};
OP.prototype.unwatch=function(a){if(a=a||window.document.body)if(KP(this,0),a!=window.document.body?SP(this,a):RP(this,window.document.body,"mouseover"),a=FP(a),delete this.ra[a],delete this.Fa[a],!(0<--this.ub)){SP(this,window.document.body);var b=this.T;this.Fb();this.T=null;window.setTimeout(function(){var a=yP();a&&b&&a.Ek(b.Mg())},100)}};OP.prototype.Kc=function(a){this.Eb.push(a)};OP.prototype.ni=function(a){_.pd(this.Eb,a)};
var LP=function(a,b,c){for(var d=[];b;){var e=EP(b);e&&a.ra[e]&&d.push(a.ra[e]);b=b.parentNode}_.rd(d,a.Eb);(0,_.id)(d,function(a){a(c)})};_.h=OP.prototype;
_.h.Sx=function(a){this.Ia=(0,_.xa)();var b=a.target||a.srcElement;if(b&&"IFRAME"!=b.tagName){for(;b&&!GP(b);)if(b=b.parentNode,1!=b.nodeType)return;if(b)if(this.$==b||this.R==b)this.V&&(window.clearTimeout(this.V),this.V=null);else{this.R=b;QP(this,b,"mousemove",this.aK);"focus"==a.type||"focusin"==a.type?(a=_.Ft(b),this.W.x=a.x,this.W.y=a.y+b.offsetHeight):(this.W.x=a.clientX,this.W.y=a.clientY);this.va=(0,_.xa)();a=this.U=HP(b,this.Fa);var c=IP("hoverDelay",a);this.T?this.T.T&&(window.clearTimeout(this.S),
this.S=window.setTimeout((0,_.u)(this.dt,this,b),c-IP("loadDelay",a))):(window.clearTimeout(this.S),this.S=window.setTimeout((0,_.u)(this.CL,this),c-IP("loadHovercardDelay",a)))}}};_.h.Ls=function(a){this.Ia=(0,_.xa)();if("blur"!=a.type||a.target==this.$||a.target==this.R){if(a=a.relatedTarget||a.toElement){if("IFRAME"==a.tagName)return;if(this.Ra)for(;a&&"BODY"!=a.tagName;){if(a==this.Ra)return;a=a.parentNode}}KP(this)}};_.h.Rx=function(){KP(this,0)};
_.h.aK=function(a){this.W.x=a.clientX;this.W.y=a.clientY};_.h.CL=function(){this.S&&(window.clearTimeout(this.S),this.S=null);if(this.R&&(LP(this,this.R,{type:"hover",config:this.U}),!this.T)){var a=this.T=new JP(this);zP((0,_.u)(function(b){b.Ot("card",PP++,a.Mg())&&a.load(this.U)},this))}};
_.h.dt=function(a){this.S&&(window.clearTimeout(this.S),this.S=null);if(this.R==a){var b=IP("hoverDelay",this.U)-IP("loadDelay",this.U)-(0,_.xa)()+this.va;if(0<b)this.S=window.setTimeout((0,_.u)(this.dt,this,a),b);else{LP(this,a,{type:"hover",config:this.U});var b=this.T,c=this.U;a=(0,_.u)(this.GC,this,a);b.T&&(b.V=a,c.ri=++b.U,b.R.send("loadData",c,void 0,_.en))}}};
_.h.GC=function(a){if(this.R===a&&this.T&&this.T.T&&this.va){var b=IP("hoverDelay",this.U)-(0,_.xa)()+this.va;0<b?window.setTimeout((0,_.u)(this.GC,this,a),b):(this.Fb(),this.$=this.R,this.Xa=this.U,RP(this,this.R,"mousemove"),this.va=this.U=this.R=null,yP().Cu(this.T.Mg()))}};var KP=function(a,b){a.R&&RP(a,a.R,"mousemove");a.R=null;a.U=null;a.va=null;a.S&&(window.clearTimeout(a.S),a.S=null);!a.V&&a.$&&(a.V=window.setTimeout((0,_.u)(a.Fb,a),_.Vc(b)?b:IP("closeDelay",a.Xa)))};
OP.prototype.Fb=function(){this.V&&(window.clearTimeout(this.V),this.V=null);this.$&&yP().Bl(this.T.Mg())};var NP=function(a,b){LP(a,null,b);a.Ta&&a.Ta.send("cardAction",b,void 0,a.Va)};OP.prototype.Mq=function(a,b,c){var d={};d.frame=a;d.filter=b||_.dn;d.Xc=c||_.na;this.ya.set(_.ed(a),d);a.register("cardAction",(0,_.u)(function(a){NP(this,a);d.Xc(a)},this),d.filter)};
OP.prototype.Nq=function(a){this.Va=a||_.dn;_.Um.U((0,_.u)(function(a){this.Ta=a;this.Ta.register("cardAction",(0,_.u)(this.Nm,this),this.Va)},this),void 0,this.Va)};OP.prototype.Nm=function(a){this.ya.isEmpty()||(0,_.id)(this.ya.Mc(),function(b){b.frame.send("cardAction",a,void 0,b.filter)});this.T&&this.T.R.send("cardAction",a,void 0,_.en)};
_.TP=function(){var a={},b=new OP;a.watch=function(a,d,e){b.watch(a,d,e)};a.unwatch=function(a){b.unwatch(a)};a.Kc=function(a){b.Kc(a)};a.ni=function(a){b.ni(a)};a.Mq=function(a,d,e){b.Mq(a,d,e)};a.Nq=function(a){b.Nq(a)};a.Nm=function(a){b.Nm(a)};a.Ha=function(a,b){b.origin=window.location.protocol+"//"+window.location.host;var e=_.Um.Qf({url:":card",where:window.document.getElementById(a),queryParams:b,messageHandlers:{_ready:function(){e.send("loadData",b,void 0,_.en)},loaded:function(){e.send("render", void 0,void 0,_.en)}},messageHandlersFilter:_.en})};return a}();
_.A("gapi.card.watch",_.TP.watch);_.A("gapi.card.unwatch",_.TP.unwatch);_.A("gapi.card.addCallback",_.TP.Kc);_.A("gapi.card.removeCallback",_.TP.ni);_.A("gapi.card.render",_.TP.Ha);_.A("gapi.card.connectChild",_.TP.Mq);_.A("gapi.card.connectOpener",_.TP.Nq);_.A("gapi.card.broadcast",_.TP.Nm);

});
// Google Inc.
